import 'package:flutter_live_score/domain/models/match_stats.dart';
import 'package:flutter_live_score/domain/models/team.dart';

class MatchGame {
  MatchGame({
    required this.week,
    required this.location,
    required this.live,
    required this.duration,
    required this.date,
    required this.teamHome,
    required this.teamAway,
  });
  int week;
  String location;
  MatchStats teamHome;
  MatchStats teamAway;
  int duration;
  DateTime date;
  bool live;
  String get heroTag => teamHome.team.name + teamAway.team.name;
  int get totalGoals => teamHome.goals + teamAway.goals;
}

List<MatchGame> listGame = [
  MatchGame(
    week: 10,
    location: 'St James Park',
    live: true,
    duration: 83,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[0],
        goals: 0,
        type: TypeTeam.home,
        shotsOnGoal: 2,
        shots: 4,
        possession: 0.26,
        yellowCard: 3,
        cornerKicks: 0,
        crosses: 10,
        goalkeeperSaves: 3,
        goalkKicks: 10),
    teamAway: MatchStats(
        team: Team.listTeam[1],
        goals: 3,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 15,
        possession: 0.74,
        yellowCard: 2,
        cornerKicks: 2,
        crosses: 23,
        goalkeeperSaves: 2,
        goalkKicks: 2),
  ),
  MatchGame(
    week: 10,
    location: 'Santiago Bernabéu',
    live: true,
    duration: 74,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[2],
        goals: 2,
        type: TypeTeam.home,
        shotsOnGoal: 2,
        shots: 4,
        possession: 0.69,
        yellowCard: 3,
        cornerKicks: 6,
        crosses: 15,
        goalkeeperSaves: 3,
        goalkKicks: 10),
    teamAway: MatchStats(
        team: Team.listTeam[3],
        goals: 3,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 9,
        possession: 0.31,
        yellowCard: 5,
        cornerKicks: 7,
        crosses: 12,
        goalkeeperSaves: 2,
        goalkKicks: 7),
  ),
  MatchGame(
    week: 10,
    location: 'Matute',
    live: true,
    duration: 55,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[4],
        goals: 5,
        type: TypeTeam.home,
        shotsOnGoal: 5,
        shots: 4,
        possession: 0.40,
        yellowCard: 2,
        cornerKicks: 6,
        crosses: 10,
        goalkeeperSaves: 3,
        goalkKicks: 10),
    teamAway: MatchStats(
        team: Team.listTeam[5],
        goals: 3,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 9,
        possession: 0.60,
        yellowCard: 4,
        cornerKicks: 7,
        crosses: 8,
        goalkeeperSaves: 2,
        goalkKicks: 7),
  ),
  MatchGame(
    week: 10,
    location: 'Old Trafford​',
    live: true,
    duration: 30,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[6],
        goals: 0,
        type: TypeTeam.home,
        shotsOnGoal: 5,
        shots: 4,
        possession: 0.33,
        yellowCard: 2,
        cornerKicks: 6,
        crosses: 10,
        goalkeeperSaves: 3,
        goalkKicks: 10),
    teamAway: MatchStats(
        team: Team.listTeam[7],
        goals: 1,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 9,
        possession: 0.67,
        yellowCard: 4,
        cornerKicks: 7,
        crosses: 8,
        goalkeeperSaves: 2,
        goalkKicks: 7),
  ),
  //* game over
  MatchGame(
    week: 10,
    location: 'Olímpico Atatürk',
    live: false,
    duration: 90,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[8],
        goals: 0,
        type: TypeTeam.home,
        shotsOnGoal: 5,
        shots: 4,
        possession: 0.55,
        yellowCard: 0,
        cornerKicks: 3,
        crosses: 10,
        goalkeeperSaves: 3,
        goalkKicks: 8),
    teamAway: MatchStats(
        team: Team.listTeam[9],
        goals: 1,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 0,
        possession: 0.45,
        yellowCard: 2,
        cornerKicks: 9,
        crosses: 8,
        goalkeeperSaves: 2,
        goalkKicks: 11),
  ),
  MatchGame(
    week: 10,
    location: 'Camp Nou',
    live: false,
    duration: 90,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[10],
        goals: 2,
        type: TypeTeam.home,
        shotsOnGoal: 5,
        shots: 4,
        possession: 0.36,
        yellowCard: 5,
        cornerKicks: 3,
        crosses: 10,
        goalkeeperSaves: 3,
        goalkKicks: 8),
    teamAway: MatchStats(
        team: Team.listTeam[11],
        goals: 6,
        type: TypeTeam.away,
        shotsOnGoal: 12,
        shots: 0,
        possession: 0.64,
        yellowCard: 7,
        cornerKicks: 3,
        crosses: 8,
        goalkeeperSaves: 2,
        goalkKicks: 5),
  ),
  MatchGame(
    week: 10,
    location: 'Parken',
    live: false,
    duration: 90,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[12],
        goals: 0,
        type: TypeTeam.home,
        shotsOnGoal: 5,
        shots: 4,
        possession: 0.25,
        yellowCard: 0,
        cornerKicks: 3,
        crosses: 10,
        goalkeeperSaves: 3,
        goalkKicks: 8),
    teamAway: MatchStats(
        team: Team.listTeam[13],
        goals: 1,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 0,
        possession: 0.75,
        yellowCard: 2,
        cornerKicks: 9,
        crosses: 8,
        goalkeeperSaves: 2,
        goalkKicks: 11),
  ),
  MatchGame(
    week: 10,
    location: 'Vodafone Park',
    live: false,
    duration: 90,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[14],
        goals: 2,
        type: TypeTeam.home,
        shotsOnGoal: 5,
        shots: 4,
        possession: 0.12,
        yellowCard: 0,
        cornerKicks: 3,
        crosses: 10,
        goalkeeperSaves: 13,
        goalkKicks: 18),
    teamAway: MatchStats(
        team: Team.listTeam[15],
        goals: 3,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 10,
        possession: 0.88,
        yellowCard: 3,
        cornerKicks: 9,
        crosses: 8,
        goalkeeperSaves: 12,
        goalkKicks: 21),
  ),
  MatchGame(
    week: 10,
    location: 'Enrique Roca',
    live: false,
    duration: 90,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[16],
        goals: 5,
        type: TypeTeam.home,
        shotsOnGoal: 5,
        shots: 4,
        possession: 0.75,
        yellowCard: 3,
        cornerKicks: 3,
        crosses: 10,
        goalkeeperSaves: 13,
        goalkKicks: 18),
    teamAway: MatchStats(
        team: Team.listTeam[17],
        goals: 3,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 10,
        possession: 0.25,
        yellowCard: 5,
        cornerKicks: 9,
        crosses: 8,
        goalkeeperSaves: 12,
        goalkKicks: 21),
  ),
  MatchGame(
    week: 10,
    location: 'Stamford Bridge',
    live: false,
    duration: 90,
    date: DateTime.now(),
    teamHome: MatchStats(
        team: Team.listTeam[18],
        goals: 8,
        type: TypeTeam.home,
        shotsOnGoal: 5,
        shots: 4,
        possession: 0.80,
        yellowCard: 3,
        cornerKicks: 3,
        crosses: 10,
        goalkeeperSaves: 13,
        goalkKicks: 18),
    teamAway: MatchStats(
        team: Team.listTeam[19],
        goals: 0,
        type: TypeTeam.away,
        shotsOnGoal: 6,
        shots: 10,
        possession: 0.20,
        yellowCard: 2,
        cornerKicks: 9,
        crosses: 8,
        goalkeeperSaves: 12,
        goalkKicks: 21),
  ),
];
